steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/akshu-hello-awesome/hello-awesome:$SHORT_SHA', '.'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/akshu-hello-awesome/hello-awesome:$SHORT_SHA'] 
